version: 2.1

jobs:
  build:
      docker:
        - image: debian:stretch 
      environment:
        GITHUB_USER: hiro-o918 
        GITHUB_PROJECT: lfs-caching
        LOCK_FILE: lfs-files.lock
      steps:
        - checkout
        - run:
            name: Install git-lfs
            command: |
              apt-get update
              apt-get -qq install curl ca-certificates
              curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
              apt-get update
              apt-get -qq install git-lfs
              mkdir -p ~/.ssh
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              ssh git@github.com git-lfs-authenticate ${GITHUB_USER}/${GITHUB_PROJECT}.git download
        - run:
            name: Generate lfs-files.lock
            command: |
              git lfs ls-files > ${LOCK_FILE}
        - restore_cache:
            key: lfs-deps-v1-{{ checksum "lfs-files.lock" }}
        - run:
            name: Resore caches from cache directroy and Pull files managed by git-lfs
            command: |
              bash scripts/lfs-restore.sh
              git lfs pull
        - run:
            name: Store lfs files to cache directroy
            command: |
              bash scripts/lfs-store.sh
        - save_cache:
            key: lfs-deps-v1-{{ checksum "lfs-files.lock" }}
            paths:
              - ./.lfs-caches

workflows:
  build-using-caching:
    jobs:
      - build
